platform :ios, '9.0'

target 'OutReach' do
  
  use_frameworks!
  
	pod "TextFieldEffects"
	pod 'Firebase/Core'
	pod 'Firebase/Auth'
	pod 'Firebase/Database'
    pod 'Firebase/Storage'
  # Pods for OutReach

end
